name: Deploy to Fly
on: [push]
jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: FlyV1 fm2_lJPECAAAAAAAAlnOxBCtPuB1YvRmJEFJu8NETeFOwrVodHRwczovL2FwaS5mbHkuaW8vdjGUAJLOAAq0rB8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDyr/3g3TjxmmzpIhEfdHFb4LS7NdgYdjrMdayyALKgUdHVaRelu2fUSRJtN/uRIflRKVE1dq7AYiwQ/10rETm7NRG+LKPoLuLNFXGkVWXBFINx1zQhzxn8OuR7TnhxKJl9lSPKU2usbkN4OhoBhAjY9Y2Nhyuy1GSd607VPPp3iCfrkh4Fa+uEpTOJh4cQgMHVv3+DP52EUfBK/KwcIoaBsmdJm8n5vgfHLTcYuxUY=,fm2_lJPETm7NRG+LKPoLuLNFXGkVWXBFINx1zQhzxn8OuR7TnhxKJl9lSPKU2usbkN4OhoBhAjY9Y2Nhyuy1GSd607VPPp3iCfrkh4Fa+uEpTOJh4cQQPhtJL4tIWdse9DTYcSQ4zcO5aHR0cHM6Ly9hcGkuZmx5LmlvL2FhYS92MZYEks5l+U0SzwAAAAEh8WswCpHOAApwEgzEEE3YdnXV6IBUP+etM+/mDyTEIFKrdJE0TqSWucYp2k4Jt/Bp8LaVbmiPZJBff2pYK6jo