name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 
        with:
          heroku_api_key: "d6d55208-ecf2-4757-8997-454a1d4b60f5"
          heroku_app_name: "bil481project" 
          heroku_email: "mkaratekin@etu.edu.tr"