name: 'Netlify Deploy'

on:
  release:
    types: ['published']

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@main
        with:
          NETLIFY_AUTH_TOKEN: nfp_pyeS8zmmNJyzVt78scd65bgStsckdWdv7b4a
          NETLIFY_SITE_ID: 4fc48113-b688-45f1-9dae-4c6ac4bcdbe1
          NETLIFY_DEPLOY_TO_PROD: true